/*
Venta de libros con BookStore
*/

/*
Diseño:

CREATE PRODECURE USP_VENTA
(
	@CLIENTE VARCHAR(150),
	@IDPUBLICACION CHAR(8),
	@CANTIDAD INT,
	@IDEMPLEADO INT,
	@IDVENTA INT OUT,
	@IDESTADO INT OUT
)
AS

*/


CREATE PROCEDURE USP_VENTA
(
	@CLIENTE VARCHAR(150),
	@IDPUBLICACION CHAR(8),
	@CANTIDAD INT,
	@IDEMPLEADO INT,
	@IDVENTA INT OUT,
	@IDESTADO INT OUT
)
AS
	DECLARE @PORCDCTO DECIMAL(5,2),     @DCTO MONEY,    @SUBTOTAL MONEY,
	        @IMPUESTO MONEY,            @TOTAL MONEY,   @PRECIO MONEY
BEGIN 
	TRY
		-- Paso 1
		BEGIN TRANSACTION;
		-- Paso 6: Obtener porcentaje de descuento
		SELECT @PORCDCTO = porcentaje FROM PROMOCION
		WHERE @CANTIDAD>= cantmin AND @CANTIDAD<=cantmax;
		-- paso 7: Calcular venta
		SELECT @PRECIO = PRECIO FROM PUBLICACION
		WHERE idpublicacion = @IDPUBLICACION;
		SET @DCTO = @PRECIO * @CANTIDAD * @PORCDCTO;
		SET @TOTAL = @PRECIO * @CANTIDAD - @DCTO;
		-- Paso 10 
		COMMIT TRANSACTION; 
	END TRY 
	BEGIN CATCH 
		ROLLBACK TRANSACTION; 
	END CATCH
END;
GO

SELECT * FROM PROMOCION;
SELECT * FROM CONTROL;